// @Author: abbeymart | Abi Akindele | @Created: 2020-12-23 | @Updated: 2020-12-23
// @Company: mConnect.biz | @License: MIT
// @Description: mConnect datatypes' constants

package datatypes

const (
	String             = "string"
	Text               = "text"
	StringAlpha        = "stringalpha"
	StringAlphaNumeric = "stringalphanumeric"
	PostalCode         = "postalcode"
	MongoDBId          = "mongodbid"
	UUID               = "uuid"
	UUID3              = "uuid3"
	UUID4              = "uuid4"
	UUID5              = "uuid5"
	MD4                = "md4"
	MD5                = "md5"
	SHA1               = "sha1"
	SHA256             = "sha2"
	SHA384             = "sha3"
	SHA512             = "sha5"
	Number             = "number"
	Integer            = "integer"
	Decimal            = "decimal"
	Float              = "float"
	Float32            = "float32"
	Float64            = "float64"
	BigInt             = "bigint"
	BigFloat           = "bigfloat"
	Object             = "object"
	Array              = "array"
	ArrayOfString      = "arrayofstring"
	ArrayOfNumber      = "arrayofnumber"
	ArrayOfBoolean     = "arrayofboolean"
	ArrayOfStruct      = "arrayofstruct"
	ArrayOfMap         = "arrayofmap"
	Boolean            = "boolean"
	Bool               = "boolean"
	JSON               = "json"
	DateTime           = "datetime"
	Date               = "date"
	Time               = "time"
	TimeStamp          = "timestamp"
	TimeStampZ         = "timestampz"
	Positive           = "positive"
	Natural            = "natural"
	Negative           = "negative"
	Email              = "email"
	URL                = "url"
	DomainName         = "domainname"
	Port               = "port"
	IP                 = "ip"
	IP4                = "ip4"
	IP6                = "ip6"
	JWT                = "jwt"
	Latitude           = "latitude"
	Longitude          = "longitude"
	ISO2               = "iso2"
	ISO3               = "iso3"
	MACAddress         = "macaddress"
	Mime               = "mime"
	CreditCard         = "creditcard"
	Currency           = "currency"
	IMEI               = "imei"
	Set                = "set"
	Map                = "map"
	Undefined          = "undefined"
)
